FROM node:22-alpine3.19
MAINTAINER Jordan Denison <jordan@denisonweb.com>

RUN mkdir -p /usr/src/app /usr/src/cache
WORKDIR /usr/src/cache

COPY package.json ./
COPY package-lock.json ./
COPY local-packages/backend-0.0.0.tgz ./local-packages/

RUN npm install --location=global npm@10.9.1 && chown -R node:node /usr/src/cache

USER node

RUN npm install

WORKDIR /usr/src/app