name: Deploy SPA

on:
  push:
    branches:
      - disabled

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run docker compose and tests
        id: test-code
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          printf "\n[auth]\ntoken=${{ secrets.SENTRY_TOKEN }}\n" > .sentryclirc
          npm ci
          npm test
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::1234567891011:role/GithubActions
          aws-region: us-east-2

      - name: Deploy to S3
        run: |
          aws s3 sync build/ s3://${{ secrets.AWS_S3_BUCKET }} --delete --follow-symlinks
        env:
          AWS_REGION: 'us-east-2'

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
          PATHS: "/index.html"
          AWS_REGION: "us-east-2"